server:
  port: 8050
  servlet:
    context-path: /cm
#   application-display-name: CooRush  
  shutdown: graceful # 优雅关机(勿强制杀死进程)

spring:
  profiles:
    active: dev
  application:
    name: CM
#  cloud:
#    config:
#      enabled: false

# 日志文件位置
logging:
  config: classpath:log4j2-spring.xml # 这个是默认的，可以不写，换了名字就要写
  level:
    cn.jay.repository: trace
 
 
 